In [1]:
import torch

In [2]:
x=torch.empty(5,3)
x

tensor(1.00000e-42 *
       [[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  1.9954,  0.0000],
        [ 0.0000,  0.5815,  0.0000]])

In [4]:
x=torch.rand(5,3)
x


tensor([[ 0.1053,  0.5353,  0.8800],
        [ 0.9853,  0.9285,  0.6932],
        [ 0.4308,  0.7316,  0.2367],
        [ 0.4415,  0.7189,  0.4075],
        [ 0.2916,  0.3506,  0.8317]])

In [8]:
x=torch.zeros(5,3,dtype=torch.long)
x


tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])

In [9]:
torch.tensor([5.678,4.32])

tensor([ 5.6780,  4.3200])

In [13]:
x=torch.rand(5,4)
y=torch.rand(5,4)

In [14]:
print(x+y)


tensor([[ 1.0064,  0.4612,  1.5594,  0.8955],
        [ 1.1028,  1.6567,  1.3924,  0.2522],
        [ 1.6315,  0.2650,  0.5116,  1.3129],
        [ 1.0971,  0.1237,  0.9263,  0.8535],
        [ 1.2980,  0.6658,  0.9882,  1.0104]])


In [15]:
print(torch.add(x,y))

tensor([[ 1.0064,  0.4612,  1.5594,  0.8955],
        [ 1.1028,  1.6567,  1.3924,  0.2522],
        [ 1.6315,  0.2650,  0.5116,  1.3129],
        [ 1.0971,  0.1237,  0.9263,  0.8535],
        [ 1.2980,  0.6658,  0.9882,  1.0104]])


In [16]:
result=torch.empty(5,4)
torch.add(x,y,out=result)

tensor([[ 1.0064,  0.4612,  1.5594,  0.8955],
        [ 1.1028,  1.6567,  1.3924,  0.2522],
        [ 1.6315,  0.2650,  0.5116,  1.3129],
        [ 1.0971,  0.1237,  0.9263,  0.8535],
        [ 1.2980,  0.6658,  0.9882,  1.0104]])

In [18]:
y=y+x
y

tensor([[ 1.3756,  0.7406,  2.3380,  1.7678],
        [ 1.6209,  2.5281,  1.7935,  0.3663],
        [ 2.5417,  0.3258,  0.8975,  2.1289],
        [ 1.2966,  0.1661,  1.4856,  1.4915],
        [ 1.7057,  0.7714,  1.6637,  1.9921]])

In [22]:
print(y[2:4,2])

tensor([ 0.8975,  1.4856])


In [39]:
x=torch.ones(2,2, requires_grad=True)
print(x)
z=torch.ones(2,2,requires_grad=True)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [40]:
y=(4*x)+2+(5*z);

In [41]:
y.backward(x)
y.backward(z)

In [43]:
print(x.grad)
print(z.grad)

tensor([[ 8.,  8.],
        [ 8.,  8.]])
tensor([[ 10.,  10.],
        [ 10.,  10.]])
