In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [32]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.conv1=nn.Conv2d(1,6,5)
        self.conv2=nn.Conv2d(6,16,5)
        
        self.fc1=nn.Linear(16*5*5,120)
        self.fc2=nn.Linear(120,84)
        self.fc3=nn.Linear(84,10)
        
    def forward(self,x):
        x=F.max_pool2d(F.relu(self.conv1(x)),(2,2))
        x=F.max_pool2d(F.relu(self.conv2(x)),(2,2))
        x=x.view(-1,self.num_flat_features(x))
        x=F.relu(self.fc1(x))
        x=F.relu(self.fc2(x))
        x=self.fc3(x)
        return x
    
    def num_flat_features(self,x):
        size=x.size()[1:]
        num_features=1
        for s in size:
            num_features*=s
        return num_features
    
net=Net()
print(net)
        
        

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [10]:
param=list(net.parameters())
print(param[0])
param=len(param)
param


Parameter containing:
tensor([[[[ 0.0543,  0.0266, -0.0749, -0.1747,  0.0587],
          [ 0.0361,  0.0578,  0.1566,  0.0486, -0.1795],
          [-0.0110,  0.1023, -0.1752,  0.1697, -0.0679],
          [-0.0185,  0.0646, -0.1195, -0.0743, -0.1270],
          [ 0.1933,  0.1270,  0.1967,  0.0127, -0.0249]]],


        [[[ 0.1438, -0.1182,  0.0576, -0.1798, -0.0974],
          [ 0.0225, -0.0420,  0.0215,  0.1392, -0.0123],
          [ 0.1054, -0.0633, -0.1609, -0.0870,  0.1990],
          [-0.0112, -0.1917, -0.0874,  0.1171,  0.1049],
          [-0.0319, -0.0230, -0.0258,  0.0283,  0.1366]]],


        [[[-0.0259, -0.0772,  0.0580, -0.0411, -0.1546],
          [-0.1777,  0.0445,  0.1319, -0.1979, -0.0273],
          [-0.1902,  0.1563,  0.0438, -0.1266, -0.0887],
          [ 0.0622,  0.1142, -0.1671,  0.1522, -0.0629],
          [ 0.1235, -0.0361,  0.0181,  0.1181,  0.0244]]],


        [[[ 0.1016,  0.0727, -0.1038,  0.1396, -0.0190],
          [ 0.1813, -0.0004, -0.0208, -0.1991,  0.1808

10

In [33]:
inp=torch.randn(1,1,32,32)
out=net(inp)
print(out)

tensor([[-0.1370,  0.0707,  0.1266, -0.0495,  0.1093, -0.1640,  0.0317,
          0.0546,  0.1424, -0.0706]])


In [34]:
#loss function
output=net(inp)
target=torch.arange(1,11)
print(target)
target=target.view(1,-1)
print(target)
criterion=nn.MSELoss()
loss=criterion(output,target)
print(loss)

tensor([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])
tensor([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]])
tensor(38.3146)


In [35]:
print(loss.grad_fn)

In [40]:


print("conv1.bias.grad before backward")
print(net.conv1.bias.grad)

loss.backward()

print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([ 0.,  0.,  0.,  0.,  0.,  0.])


RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.